---
# subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker-operator
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: {{ $.Values.channel }} # Use the appropriate channel, e.g., 7.x
  name: {{ $.Values.name }} # Check OperatorHub for the exact package name
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
